export default {
    "list": [{
        "letter": "A",
        "data": []
    }, {
        "letter": "B",
        "data": []
    }, {
        "letter": "C",
        "data": []
    }, {
        "letter": "D",
        "data": []
    }, {
        "letter": "E",
        "data": []
    }, {
        "letter": "F",
        "data": []
    }, {
        "letter": "G",
        "data": [
            "GalChat团队",
        ]
    }, {
        "letter": "H",
        "data": []
    }, {
        "letter": "I",
        "data": []
    }, {
        "letter": "J",
        "data": []
    }, {
        "letter": "K",
        "data": []
    }, {
        "letter": "L",
        "data": []
    }, {
        "letter": "M",
        "data": []
    }, {
        "letter": "N",
        "data": []
    }, {
        "letter": "O",
        "data": []
    }, {
        "letter": "P",
        "data": []
    }, {
        "letter": "Q",
        "data": []
    }, {
        "letter": "R",
        "data": []
    }, {
        "letter": "S",
        "data": []
    }, {
        "letter": "T",
        "data": []
    }, {
        "letter": "U",
        "data": []
    }, {
        "letter": "V",
        "data": []
    }, {
        "letter": "W",
        "data": []
    }, {
        "letter": "X",
        "data": []
    }, {
        "letter": "Y",
        "data": []
    }, {
        "letter": "Z",
        "data": []
    }]
}
